// <auto-generated />
using System;
using DemoDocuments.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoDocuments.Server.Data.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20261002003344_FilterInboxIndex")]
    partial class FilterInboxIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoDocuments.Server.Domain.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DivisionHeadActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.DocumentBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentTypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InternalDueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Revision")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("DocNumber");

                    b.HasIndex("GroupId");

                    b.ToTable("Documents", (string)null);

                    b.HasDiscriminator<string>("DocumentTypeDiscriminator").HasValue("DocumentBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.Person", b =>
                {
                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("ActorId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionLeadActorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DivisionId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedSectionId")
                        .HasColumnType("int");

                    b.Property<double>("CompletionPercentage")
                        .HasColumnType("float")
                        .HasColumnName("CompletionPercentage");

                    b.Property<string>("CurrentlyAssignedActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkItemState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSectionId");

                    b.HasIndex("DocumentId", "AssignedSectionId")
                        .IsUnique();

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.ForkManifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvergenceTaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ForkGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginTaskId")
                        .HasColumnType("int");

                    b.Property<int?>("SubWorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForkGroupId")
                        .IsUnique();

                    b.ToTable("TaskRouterForkManifests", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.ForkManifestEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BranchNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchOutcomeKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForkManifestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ForkManifestId", "BranchKey")
                        .IsUnique();

                    b.ToTable("TaskRouterForkManifestEntries", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.OutcomeTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("TaskRouterOutcomeTypes", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.PreAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BranchKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("WorkflowRunId", "TaskDefinitionId")
                        .IsUnique();

                    b.ToTable("TaskRouterPreAssignments", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.SubWorkflowAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubWorkflowDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowDefinitionVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubWorkflowDefinitionId");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("WorkflowDefinitionVersionId", "TaskDefinitionId", "SubWorkflowDefinitionId")
                        .IsUnique();

                    b.ToTable("TaskRouterSubWorkflowAttachments", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.SubWorkflowInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentTaskId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubWorkflowDefinitionVersionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("SubWorkflowDefinitionVersionId");

                    b.HasIndex("WorkflowRunId", "Status");

                    b.ToTable("TaskRouterSubWorkflowInstances", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TaskOutcomeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("OutcomeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId", "OutcomeKey")
                        .IsUnique();

                    b.ToTable("TaskRouterTaskOutcomes", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TaskRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReworkRoute")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NextTaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("TaskOutcomeDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextTaskDefinitionId");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("TaskOutcomeDefinitionId");

                    b.ToTable("TaskRouterTaskRoutes", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TaskTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("TaskRouterTaskTypes", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TriggerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomEventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispatchMode")
                        .HasColumnType("int");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<int>("FailurePolicy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("TriggerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId", "Event");

                    b.ToTable("TaskRouterTriggerDefinitions", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TriggerExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TriggerDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TaskId", "Event");

                    b.ToTable("TaskRouterTriggerExecutions", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubWorkflow")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TaskRouterDefinitions", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowDefinitionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CarryAssignmentForward")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntryTaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Version")
                        .IsUnique();

                    b.HasIndex("SubjectType", "IsPublished", "IsLatest");

                    b.ToTable("TaskRouterDefinitionVersions", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowOutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomEventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispatchMode")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LeasedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TriggerDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("TaskRouterOutbox", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowDefinitionVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionVersionId");

                    b.ToTable("TaskRouterRuns", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBranchKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssignedToActorId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConvergenceTaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ForkGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ForkManifestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForkOrigin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutcomeKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OverdueFiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubWorkflowInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForkGroupId");

                    b.HasIndex("ForkManifestId")
                        .IsUnique()
                        .HasFilter("[ForkManifestId] IS NOT NULL AND [Status] <> 3");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("SubWorkflowInstanceId");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("WorkflowRunId");

                    b.HasIndex("AssignedToActorId", "Status")
                        .HasFilter("[Status] IN (0, 1)");

                    b.HasIndex("Status", "ReminderSentAt")
                        .HasFilter("[ReminderSentAt] IS NULL");

                    b.HasIndex("Status", "OverdueFiredAt", "DueDate")
                        .HasFilter("[OverdueFiredAt] IS NULL");

                    b.ToTable("TaskRouterTasks", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTaskDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignmentRoleKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAdHoc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConvergencePoint")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForkable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReminderLeadTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("TaskTypeDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowDefinitionVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskTypeDefinitionId");

                    b.HasIndex("WorkflowDefinitionVersionId");

                    b.ToTable("TaskRouterTaskDefinitions", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskRouterTaskLogs", (string)null);
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkflowRunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId", "TaskId", "Name")
                        .IsUnique()
                        .HasFilter("[TaskId] IS NOT NULL");

                    b.ToTable("TaskRouterVariables", (string)null);
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.ChangeRequest", b =>
                {
                    b.HasBaseType("DemoDocuments.Server.Domain.DocumentBase");

                    b.Property<string>("CogCoordinatorActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEntered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReplyReceived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReplyRequiredBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClassChange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepairChange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReplyRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Originator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ChangeRequest");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.Drawing", b =>
                {
                    b.HasBaseType("DemoDocuments.Server.Domain.DocumentBase");

                    b.Property<string>("DrawingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SheetCount")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("DW");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.DocumentBase", b =>
                {
                    b.HasOne("DemoDocuments.Server.Domain.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.Section", b =>
                {
                    b.HasOne("DemoDocuments.Server.Domain.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.WorkItem", b =>
                {
                    b.HasOne("DemoDocuments.Server.Domain.Section", "AssignedSection")
                        .WithMany()
                        .HasForeignKey("AssignedSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoDocuments.Server.Domain.DocumentBase", "Document")
                        .WithMany("WorkItems")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSection");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.ForkManifestEntry", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.ForkManifest", "ForkManifest")
                        .WithMany("Entries")
                        .HasForeignKey("ForkManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForkManifest");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.PreAssignment", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "TaskDefinition")
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.WorkflowRun", "Run")
                        .WithMany()
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.SubWorkflowAttachment", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowDefinition", "SubWorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("SubWorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "TaskDefinition")
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaskRouter.Core.Model.WorkflowDefinitionVersion", "DefinitionVersion")
                        .WithMany("SubWorkflowAttachments")
                        .HasForeignKey("WorkflowDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefinitionVersion");

                    b.Navigation("SubWorkflowDefinition");

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.SubWorkflowInstance", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowTask", "ParentTask")
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.WorkflowDefinitionVersion", "DefinitionVersion")
                        .WithMany()
                        .HasForeignKey("SubWorkflowDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefinitionVersion");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TaskOutcomeDefinition", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "TaskDefinition")
                        .WithMany("ValidOutcomes")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TaskRoute", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "NextTaskDefinition")
                        .WithMany()
                        .HasForeignKey("NextTaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "TaskDefinition")
                        .WithMany("OutgoingRoutes")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.TaskOutcomeDefinition", "Outcome")
                        .WithMany()
                        .HasForeignKey("TaskOutcomeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NextTaskDefinition");

                    b.Navigation("Outcome");

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.TriggerDefinition", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "TaskDefinition")
                        .WithMany("Triggers")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowDefinitionVersion", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowRun", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowDefinitionVersion", "DefinitionVersion")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TaskRouter.Core.Model.WorkflowSubject", "Subject", b1 =>
                        {
                            b1.Property<int>("WorkflowRunId")
                                .HasColumnType("int");

                            b1.Property<string>("SubjectId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SubjectId");

                            b1.Property<string>("SubjectType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SubjectType");

                            b1.HasKey("WorkflowRunId");

                            b1.HasIndex("SubjectType", "SubjectId");

                            b1.ToTable("TaskRouterRuns");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunId");
                        });

                    b.Navigation("DefinitionVersion");

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTask", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.ForkManifest", "ForkManifest")
                        .WithMany()
                        .HasForeignKey("ForkManifestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskRouter.Core.Model.WorkflowTask", "ParentTask")
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskRouter.Core.Model.WorkflowTaskDefinition", "TaskDefinition")
                        .WithMany()
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.WorkflowRun", "Run")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForkManifest");

                    b.Navigation("ParentTask");

                    b.Navigation("Run");

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTaskDefinition", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.TaskTypeDefinition", "TaskType")
                        .WithMany()
                        .HasForeignKey("TaskTypeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskRouter.Core.Model.WorkflowDefinitionVersion", "WorkflowDefinitionVersion")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskType");

                    b.Navigation("WorkflowDefinitionVersion");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTaskLog", b =>
                {
                    b.HasOne("TaskRouter.Core.Model.WorkflowTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DemoDocuments.Server.Domain.DocumentBase", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.ForkManifest", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowDefinitionVersion", b =>
                {
                    b.Navigation("SubWorkflowAttachments");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowRun", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TaskRouter.Core.Model.WorkflowTaskDefinition", b =>
                {
                    b.Navigation("OutgoingRoutes");

                    b.Navigation("Triggers");

                    b.Navigation("ValidOutcomes");
                });
#pragma warning restore 612, 618
        }
    }
}
